### ISSUE TITLE
How to change the face detection confidence value?

### ISSUE THREAD

**Issue by Maharshi-Aupera** [aqeelanwar/MaskTheFace#11]
Hi @aqeelanwar,

Thanks for your great work! 
Sometimes the faces are not detected from the dlib face detector. Could you please let me know if there is any place where I can set a lower face detection confidence value in the code?

I had the saw that in the `detector(image, int for upsample)`. I believe, the second argument for upsampling would upsample the image by a factor and then try to detect the face, if it is so, I tried that but it did not work for a few low quality images.

Thanking you in anticipation.

**Comment by ldjmgls** [comment]
Hi @Maharshi-Aupera, 

I face the same issue, how did you solve it at last?
I appreciate it if you could share any solution!
