### ISSUE TITLE
NoSectionError: No Section: 'surgical blue' 

### ISSUE THREAD

**Issue by krakshil** [aqeelanwar/MaskTheFace#9]
this error shows up everytime 'random' category of mask_type argument is is passed. It is working for other types of masks, the error is for only 'surgical blue' mask type.

**Comment by aqeelanwar** [comment]
The mask type 'surgical_blue' has been depreceated. In order to create a blue surgical mask, use the --code format explained in thre readme file. You can set the --code input as follows to create a surgical mask with blue color (#0000FF)
`--code surgical-##0000FF`

Let me know if this works.

**Comment by aqeelanwar** [comment]
Alternatively, I have updated the mask.cfg file to address this issue. Download the latest masks.cfg file and place it in `masks/masks.cfg` 
This will solve the issue.

**Comment by krakshil** [comment]
Thank you
